set(_CATKIN_CURRENT_PACKAGE "hrc_discrim_learning")
set(hrc_discrim_learning_VERSION "0.0.0")
set(hrc_discrim_learning_MAINTAINER "kayleigh bishop <kayleigh.bishop@yale.edu>")
set(hrc_discrim_learning_PACKAGE_FORMAT "2")
set(hrc_discrim_learning_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(hrc_discrim_learning_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(hrc_discrim_learning_BUILDTOOL_DEPENDS "catkin")
set(hrc_discrim_learning_BUILDTOOL_EXPORT_DEPENDS )
set(hrc_discrim_learning_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(hrc_discrim_learning_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(hrc_discrim_learning_TEST_DEPENDS )
set(hrc_discrim_learning_DOC_DEPENDS )
set(hrc_discrim_learning_URL_WEBSITE "")
set(hrc_discrim_learning_URL_BUGTRACKER "")
set(hrc_discrim_learning_URL_REPOSITORY "")
set(hrc_discrim_learning_DEPRECATED "")